---


- name: Create App"
  include_tasks: single.yml
  when:
    - k8s_simple_proxied_app is defined


- name: Create Apps"
  include_tasks: single.yml
  loop: "{{ k8s_simple_proxied_apps if k8s_simple_proxied_apps is defined else [] }}"
  loop_control:
    loop_var: k8s_simple_proxied_app
  when:
    - k8s_simple_proxied_apps is defined
    - k8s_simple_proxied_app is undefined
